package dbusserver

// Explicit routing inventory: adding an exported method requires classification.
type methodPrivilege uint8

const (
	queryPublic methodPrivilege = iota
	queryJournal
	privilegedRead
	administrative
	maintenance
	disabledOperation
)

type methodPolicy struct {
	privilege methodPrivilege
	action    string
}

var methodPolicies = map[string]methodPolicy{
	"Preparation.GetStatus":       {queryPublic, ""},
	"Preparation.Retry":           {administrative, ""},
	"Backup.CreateConfig":         {administrative, ""},
	"Backup.ListConfigs":          {privilegedRead, "org.lyraos.vega.backup.read-admin"},
	"Backup.RunBackupNow":         {administrative, ""},
	"Backup.ListSnapshots":        {privilegedRead, "org.lyraos.vega.backup.read-admin"},
	"Backup.RestoreSnapshot":      {administrative, ""},
	"Backup.DeleteConfig":         {administrative, ""},
	"Backup.ListSnapshotPaths":    {privilegedRead, "org.lyraos.vega.backup.read-admin"},
	"Backup.RestoreItems":         {administrative, ""},
	"Bluetooth.Status":            {queryPublic, ""},
	"Bluetooth.ListDevices":       {queryPublic, ""},
	"Bluetooth.SetPowered":        {administrative, ""},
	"Bluetooth.SetDiscoverable":   {administrative, ""},
	"Bluetooth.SetPairable":       {administrative, ""},
	"Bluetooth.SetScanning":       {administrative, ""},
	"Bluetooth.Pair":              {administrative, ""},
	"Bluetooth.Trust":             {administrative, ""},
	"Bluetooth.Connect":           {administrative, ""},
	"Bluetooth.Disconnect":        {administrative, ""},
	"Bluetooth.Remove":            {administrative, ""},
	"Bluetooth.SendFile":          {administrative, ""},
	"Bluetooth.StartFileReceiver": {administrative, ""},
	"DateTime.Status":             {queryPublic, ""},
	"DateTime.ListTimezones":      {queryPublic, ""},
	"DateTime.ListLocales":        {queryPublic, ""},
	"DateTime.ListKeymaps":        {queryPublic, ""},
	"DateTime.Apply":              {administrative, ""},
	"Firewall.Status":             {queryPublic, ""},
	// firewalld's config.info reads require privileged backend access. Keep
	// these two reads in the broker; a user worker would trigger its agent.
	"Firewall.ListServices":             {privilegedRead, "org.lyraos.vega.firewall.read-admin"},
	"Firewall.SetServiceEnabled":        {administrative, ""},
	"Firewall.ListPorts":                {privilegedRead, "org.lyraos.vega.firewall.read-admin"},
	"Firewall.AddPort":                  {administrative, ""},
	"Firewall.RemovePort":               {administrative, ""},
	"Software.NonFreeFirmwareStatus":    {queryPublic, ""},
	"Software.InstallNonFreeFirmware":   {disabledOperation, ""},
	"Hardware.Inventory":                {queryPublic, ""},
	"Hardware.InventoryLocalized":       {queryPublic, ""},
	"Hardware.SwitchNvidiaDriver":       {disabledOperation, ""},
	"Hardware.FirmwareStatus":           {queryPublic, ""},
	"Hardware.FirmwareStatusLocalized":  {queryPublic, ""},
	"Kernel.ListInstalled":              {queryPublic, ""},
	"Kernel.AvailablePackages":          {queryPublic, ""},
	"Kernel.Install":                    {administrative, ""},
	"Kernel.Remove":                     {administrative, ""},
	"Kernel.BootStatus":                 {privilegedRead, "org.lyraos.vega.kernel.read-admin"},
	"Kernel.ListBootEntries":            {privilegedRead, "org.lyraos.vega.kernel.read-admin"},
	"Kernel.ApplyBootConfig":            {administrative, ""},
	"Logs.Query":                        {queryJournal, "org.lyraos.vega.logs.read-admin"},
	"Logs.ListUnits":                    {queryJournal, "org.lyraos.vega.logs.read-admin"},
	"Metadata.Profile":                  {queryPublic, ""},
	"Metadata.Version":                  {queryPublic, ""},
	"Metadata.Capabilities":             {queryPublic, ""},
	"Monitor.Metrics":                   {queryPublic, ""},
	"Monitor.ListProcesses":             {queryPublic, ""},
	"Monitor.KillProcess":               {administrative, ""},
	"Network.ListInterfaces":            {queryPublic, ""},
	"Network.ListWifi":                  {queryPublic, ""},
	"Network.ConnectWifi":               {administrative, ""},
	"Network.Disconnect":                {administrative, ""},
	"Network.SetStaticIPv4":             {administrative, ""},
	"Network.ImportVPN":                 {administrative, ""},
	"Network.GetProxy":                  {queryPublic, ""},
	"Network.SetProxy":                  {administrative, ""},
	"Software.NvidiaStatus":             {queryPublic, ""},
	"Software.NvidiaRecovery":           {queryPublic, ""},
	"Software.InstallNvidia":            {administrative, ""},
	"Software.CheckNvidia":              {queryPublic, ""},
	"Services.ListServices":             {queryPublic, ""},
	"Services.ListServicesLocalized":    {queryPublic, ""},
	"Services.ListAllServices":          {queryPublic, ""},
	"Services.ListAllServicesLocalized": {queryPublic, ""},
	"Services.SetServiceEnabled":        {administrative, ""},
	"Services.SetServiceRunning":        {administrative, ""},
	"Services.RestartService":           {administrative, ""},
	"Snapshots.Available":               {queryPublic, ""},
	"Snapshots.ListSnapshots":           {privilegedRead, "org.lyraos.vega.snapshots.read-admin"},
	"Snapshots.CreateSnapshot":          {administrative, ""},
	"Snapshots.DiffPackages":            {privilegedRead, "org.lyraos.vega.snapshots.read-admin"},
	"Snapshots.DiffPackagesLocalized":   {privilegedRead, "org.lyraos.vega.snapshots.read-admin"},
	"Snapshots.Rollback":                {administrative, ""},
	"Snapshots.DeleteSnapshot":          {administrative, ""},
	"Snapshots.ClearSnapshots":          {administrative, ""},
	"Snapshots.SetRetentionPolicy":      {administrative, ""},
	"Software.PackageManagerName":       {queryPublic, ""},
	"Software.GetPackageDetails":        {queryPublic, ""},
	"Software.Search":                   {queryPublic, ""},
	"Software.SearchNative":             {queryPublic, ""},
	"Software.Install":                  {administrative, ""},
	"Software.Remove":                   {administrative, ""},
	"Software.ListUpdates":              {queryPublic, ""},
	"Software.ListNativeUpdates":        {queryPublic, ""},
	"Software.GetUpdateStatus":          {queryPublic, ""},
	"Software.RequestUpdateCheck":       {maintenance, ""},
	"Software.ListInstalled":            {queryPublic, ""},
	"Software.ListNativeInstalled":      {queryPublic, ""},
	"Software.UpdateAll":                {administrative, ""},
	"Software.UpdateAllNative":          {administrative, ""},
	"Software.UpdatePackage":            {administrative, ""},
	"Software.ListRepos":                {queryPublic, ""},
	"Software.SetRepoEnabled":           {administrative, ""},
	"Software.ClearCache":               {administrative, ""},
	"Software.ClearNativeCache":         {administrative, ""},
	"Software.AddRepo":                  {administrative, ""},
	"Software.TrustRepoKey":             {administrative, ""},
	"Storage.ListVolumes":               {queryPublic, ""},
	"Storage.Mount":                     {administrative, ""},
	"Storage.Unmount":                   {administrative, ""},
	"System.Version":                    {queryPublic, ""},
	"System.Ping":                       {queryPublic, ""},
	"System.Distro":                     {queryPublic, ""},
	"System.Logo":                       {queryPublic, ""},
	"System.DiskUsage":                  {queryPublic, ""},
	"Users.ListUsers":                   {queryPublic, ""},
	"Users.ListGroups":                  {queryPublic, ""},
	"Users.CreateUser":                  {administrative, ""},
	"Users.UpdateUser":                  {administrative, ""},
	"Users.RemoveUser":                  {administrative, ""},
	"Users.SetAdmin":                    {administrative, ""},
}
