post_install() {
  systemd-sysusers usr/lib/sysusers.d/vega-build.conf
  systemctl daemon-reload
  systemctl reload dbus.service 2>/dev/null || true
  systemctl enable --now vegad-update-check.timer 2>/dev/null || true
}

post_upgrade() {
  post_install
}

pre_remove() {
  systemctl disable --now vegad-update-check.timer 2>/dev/null || true
}

post_remove() {
  systemctl daemon-reload
  systemctl reload dbus.service 2>/dev/null || true
}
